
CREATE TABLE reports (
    id SERIAL PRIMARY KEY,
    month_of VARCHAR(100) NOT NULL,
    worker_name VARCHAR(100) NOT NULL,
    area_of_assignment VARCHAR(100) NOT NULL,
    name_of_church VARCHAR(100) NOT NULL,
    worship_service JSONB,
    sunday_school JSONB,
    prayer_meetings JSONB,
    bible_studies JSONB,
    mens_fellowships JSONB,
    womens_fellowships JSONB,
    youth_fellowships JSONB,
    child_fellowships JSONB,
    outreach JSONB,
    training_or_seminars JSONB,
    leadership_conferences JSONB,
    leadership_training JSONB,
    others JSONB,
    family_days JSONB,
    tithes_and_offerings JSONB,
    home_visited JSONB,
    bible_study_or_group_led JSONB,
    sermon_or_message_preached JSONB,
    person_newly_contacted JSONB,
    person_followed_up JSONB,
    person_led_to_christ JSONB,
    names JSONB,
    narrative_report TEXT,
    challenges_and_problem_encountered TEXT,
    prayer_request TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
